name: Platform PR CI

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  tests:
    name: Run Install Script Validation
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Installation
        run: |
          interactive=false clone_platform=false open_dashboard=false ./install-and-launch.sh
